name: nvbn blog
url: https://nvbn.github.io
permalink: pretty
paginate: 10
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: <!-- more -->
exclude: [node_modules, gulpfile.js]
future: true
gems:
  - jekyll-sitemap
  - jekyll-paginate
